<p>page chat</p>
<div id="liste_messages">
<?php require('apps/chat_liste.php'); ?>
</div>
<form method="POST">
<table>
	<tr>

      <td>nom</td><td><input type="text" id="nom" name="nom"/><td>
      <td>message</td><td><input type="text" id="message" name="message"/></td>

    </tr>
    <tr>
    	<td></td><td colspan="3"><input type="submit" name='action' value="ajout"/></td>
    </tr>

</table>
</form>
