
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0" /> -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> -->
        <!-- <link rel="stylesheet" type="text/css" href="<?= CSS_PATH ?>bootstrap.min.css" /> -->
        <link rel="stylesheet" type="text/css" href="public/styles/style.css" />
        <script src="public/js/jquery-2.2.3.min.js"></script>
        <script src="public/js/bootstrap.min.js"></script>
        <script src="public/js/main.js"></script>
        <title>Chat - GP</title>
    </head>
    <body>
        <div class="container">

            <?php require("apps/header.php"); ?>

            <div class="">   
            <?php 
                require("apps/chat.php"); 
                require("apps/footer.php");
            ?>         
            </div>

        </div>
    </body>
</html>